### ISSUE TITLE
Python Can't Find the 'Theano_utils' Module for Some Reason

### ISSUE THREAD

**Issue by MotorCityCobra** [llSourcell/Generative-Adversarial-Network-Demo#2]
I am absolutely, 100% sure the module 'theano_utils' is in the same Foxhound folder with everything else with a '.py' extension.

When I run the 'demo.py' file in python 3.5 from Terminal I get,
Traceback (most recent call last):
  File "/Users/[][][][][][][]/Desktop/GAN/demo.py", line 7, in <module>
    from foxhound import updates
  File "/Users/[][][][][]/Desktop/GAN/foxhound/demo.py", line 6, in <module>
    from theano_utils import shared0s, floatX, sharedX, l2norm
ImportError: No module named 'theano_utils'

I tried loading it this way (while in Python) but I'm not sure it works since I'm not in Python when I run the script.

> > > import sys
> > > sys.path.append("/Users/[][][][][][]/Desktop/GAN/foxhound")
> > > import theano_utils

**Comment by MotorCityCobra** [comment]
I wasn't using a virtual environment before. All is well now.
